### PR TITLE
Add Initial CLI support

### PR DESCRIPTION
**Pull request by cdleonard**
Very minimal support, can be used to check if power supply is recognized, dump current status and also power off/on

### CODE REVIEW

**Comment by cdleonard** [comment]
Fixed mypy and flake8 warnings

**Review by ap-- — COMMENTED** [review]
Thanks! This is super useful.

In a future PR we might consider outputting JSON or some other format to make it easier to parse the output from the CLI.

It might also be worth adding a console-scripts entry point!

**Comment by ap--** [comment]
I'll prepare a new release later today, when I'm back at my computer

**Comment by ap--** [comment]
New version `v1.5.0` is on its way to pypi. Thank you again for your contribution @cdleonard 🙏 ❤️

**Pull request merged**
