### PR TITLE
make pps.py python3 compatible

### LINKED ISSUE #2: Does not work with Python 3.x
I can't connect to my PPS-11810 using Python 3.x. It does work with Python 2.7. Here's what happens with Python 3.6:

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pps
>>> PSU = pps.PPS(port='/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0', reset=False, prom=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brennmat/voltcraft/pps.py", line 68, in __init__
    model = self.limits()
  File "/home/brennmat/voltcraft/pps.py", line 114, in limits
    s = self._query("GMAX")
  File "/home/brennmat/voltcraft/pps.py", line 97, in _query
    self._Serial.write("%s\r" % cmd)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 532, in write
    d = to_bytes(data)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'GMAX\r'

### PR DESCRIPTION
**Pull request by anyc**
This commit adds python3 compatibility. I only tested toggling the output however. It might as well fix #2

### CODE REVIEW

**Review by ap-- — APPROVED** [review]

**Comment by ap--** [comment]
Thanks @anyc  :+1: 
Nice to see that this is still useful to people. I'll do a few more cleanups.
Cheers,
Andreas :smiley:

**Comment by anyc** [comment]
I use it every (work) day. Thank you!

**Comment by ap--** [comment]
Ah sorry, I wanted to merge !

**Comment by ap--** [comment]
:sweat_smile: Okay. I'll add a readme and push it to pypi quickly to make it easier to use in the future.

**Pull request merged**
